stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/mq-search:0.0.1
      pushRemote: true
      registry: index.docker.io
timeout: 60
